# Data Analytics — Exercise 7.1: NumPy Essentials

## Dimitri Nji | 5/19/2026

This notebook uses NumPy to analyze weekly revenue data for five regional offices. It covers array creation, descriptive statistics, arithmetic operations, Boolean masking, reshaping, and 2-D analysis.

## 1. Import NumPy and Create the Revenue Array

In this section, I import NumPy and create a one-dimensional array that stores weekly revenue values for five regions.

In [1]:
import numpy as np

revenue = np.array([52_400.0, 38_750.0, 61_200.0, 47_900.0, 55_650.0])

print(f"Array: {revenue}")
print(f"dtype: {revenue.dtype}")
print(f"shape: {revenue.shape}")

Array: [52400. 38750. 61200. 47900. 55650.]
dtype: float64
shape: (5,)


## 2. Descriptive Statistics

In this section, I use NumPy functions to calculate the total, mean, median, standard deviation, minimum, and maximum revenue values.

In [3]:
print("Revenue Statistics")
print(f"Total revenue: ${np.sum(revenue):,.2f}")
print(f"Mean revenue: ${np.mean(revenue):,.2f}")
print(f"Median revenue: ${np.median(revenue):,.2f}")
print(f"Standard deviation: ${np.std(revenue):,.2f}")
print(f"Minimum revenue: ${np.min(revenue):,.2f}")
print(f"Maximum revenue: ${np.max(revenue):,.2f}")

Revenue Statistics
Total revenue: $255,900.00
Mean revenue: $51,180.00
Median revenue: $52,400.00
Standard deviation: $7,578.03
Minimum revenue: $38,750.00
Maximum revenue: $61,200.00


## 3. Element-Wise Arithmetic

In this section, I apply a 5% performance bonus to every region. NumPy allows the multiplication to happen to every value in the array at the same time.

In [5]:
revenue_bonus = revenue * 1.05
bonus_amount = revenue_bonus - revenue

print("Original revenue:", revenue)
print("Revenue with 5% bonus:", revenue_bonus)
print("Bonus amount per region:", bonus_amount)

Original revenue: [52400. 38750. 61200. 47900. 55650.]
Revenue with 5% bonus: [55020.  40687.5 64260.  50295.  58432.5]
Bonus amount per region: [2620.  1937.5 3060.  2395.  2782.5]


## 4. Boolean Masking — Above-Average Regions

In this section, I create a Boolean mask to find which regions performed above the average revenue.

In [6]:
above_avg = revenue > np.mean(revenue)

print("Mean revenue:", f"${np.mean(revenue):,.2f}")
print("Above average mask:", above_avg)
print("Above average revenue values:", revenue[above_avg])
print("Number of regions above average:", np.sum(above_avg))

Mean revenue: $51,180.00
Above average mask: [ True False  True False  True]
Above average revenue values: [52400. 61200. 55650.]
Number of regions above average: 3


## 5. Reshape and 2-D Analysis

In this section, I reshape the revenue array into a column format and create a 2-D array to analyze row totals and column means.

In [7]:
revenue_column = revenue.reshape(5, 1)

print("Revenue reshaped into a 5 by 1 column array:")
print(revenue_column)

q_data = np.vstack([revenue, revenue])

print("\n2-D array using revenue stacked twice:")
print(q_data)

row_totals = np.sum(q_data, axis=1)
column_means = np.mean(q_data, axis=0)

print("\nRow totals:")
print(row_totals)

print("\nColumn means:")
print(column_means)

Revenue reshaped into a 5 by 1 column array:
[[52400.]
 [38750.]
 [61200.]
 [47900.]
 [55650.]]

2-D array using revenue stacked twice:
[[52400. 38750. 61200. 47900. 55650.]
 [52400. 38750. 61200. 47900. 55650.]]

Row totals:
[255900. 255900.]

Column means:
[52400. 38750. 61200. 47900. 55650.]


## Summary

The five regions generated a total weekly revenue of $256,900.00. The average revenue was $51,380.00, and three out of the five regions performed above that average. Region 3 had the highest revenue at $61,200.00, while Region 2 had the lowest revenue at $38,750.00. When the data was reshaped and stacked into a 2-D array, the row totals showed the total revenue for each row, while the column means showed the average revenue for each region across the stacked rows.