# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [3]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through each row of the array, so the result prints each full row multiplied by 2. The second loop goes inside each row and works with each individual number one at a time. That is why the first loop prints arrays, while the second loop prints single numbers.

In [6]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents the whole row.
# Even though y loops through each individual number, the code is multiplying x, not y.
# That means each row gets printed multiple times.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [7]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [8]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [9]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [10]:

stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)

# This code gives an error because joined_array_1 and joined_array_2 have different shapes.
# joined_array_1 has 4 rows and 3 columns.
# joined_array_2 has 2 rows and 6 columns.
# NumPy cannot stack arrays unless they have the same shape.

ValueError: all input arrays must have the same shape

In [11]:
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [13]:

another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)

# This code gives an error because axis=1 joins side by side.
# For that to work, the arrays must have the same number of rows.
# joined_array_1 has 4 rows, but arrA has only 2 rows.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [14]:
h_stack = np.hstack((arrA, arrA))
# hstack joins the arrays horizontally, side by side.

v_stack = np.vstack((arrA, arrA))
# vstack joins the arrays vertically, one on top of the other.

d_stack = np.dstack((arrA, arrA))
# dstack stacks the arrays along a third dimension, adding depth.

print("hstack result:")
print(h_stack)

print("\nvstack result:")
print(v_stack)

print("\ndstack result:")
print(d_stack)

hstack result:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

vstack result:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

dstack result:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [15]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# The result is 2 arrays.
# Each array is two-dimensional.
# Each array has 2 rows and 3 columns.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [16]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

# The result is 3 arrays.
# Each array is still two-dimensional.
# Because 4 rows cannot split evenly into 3 groups, NumPy makes uneven groups.
# The first array has 2 rows and 3 columns.
# The second and third arrays each have 1 row and 3 columns.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [17]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")

print(result_1)

# This checks each number in arrA. If the number is even, it prints the number. If the number is not even, it prints "odd".

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [18]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [19]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [20]:
print(arrB)

y = arrB >= 7

arrD = arrB[y]

print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
