# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)

print(r_1)

[16 19]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))

print(r_2)

[[ 3 19]]


In [4]:
r_3 = np.random.rand(2, 1)

print(r_3)

[[0.78970323]
 [0.89553131]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[53 53 59 34 53]
 [56 29 45 39 30]
 [52 33 91 92 42]
 [26 35 72 64 72]]


In [6]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.6804928  0.03908466 0.07208097 0.05212958 0.9706106 ]
 [0.73613425 0.83027633 0.17510287 0.93610298 0.65344041]
 [0.76215903 0.27190696 0.46355784 0.03157523 0.7361933 ]
 [0.4227155  0.62011382 0.47781359 0.66872347 0.2367139 ]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Chelsea", "Alex", "Brian", "Maria",
    "James", "Aaliyah", "David", "Sophia",
    "Michael", "Nadia", "Chris", "Tiana"
])

print(students)

['Chelsea' 'Alex' 'Brian' 'Maria' 'James' 'Aaliyah' 'David' 'Sophia'
 'Michael' 'Nadia' 'Chris' 'Tiana']


In [8]:
call_on = np.random.choice(students)

print(call_on)

Tiana


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This may not be the best way to assign breakout groups because the same student
# can be selected more than once. That means one person could appear in multiple
# groups while another student may not be selected at all.

[['Aaliyah' 'Maria' 'Alex' 'Alex']
 ['David' 'Chris' 'Aaliyah' 'Alex']
 ['Michael' 'Tiana' 'Tiana' 'Nadia']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.05, 0.08, 0.12, 0.00, 0.07, 0.06, 0.05, 0.04, 0.08, 0.05]
)

print(call_on_weighted)

# The p values control how likely each student is to be selected.
# Chelsea has a 30% chance, so she is the most likely to be selected.
# Aaliyah has a 0% chance, so she cannot be selected.
# The other students have smaller probabilities, and all probabilities add up to 1.00.

['Nadia' 'Chelsea' 'Chelsea' 'Michael' 'Chelsea']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[13.45589071 11.4777443   4.12655817 12.77930413 17.86968646]
 [18.33711092  7.97134367  5.47872535 12.03175892  8.28232656]
 [ 8.55123002  9.63749325 10.15023863  8.50969144  4.47403094]
 [ 9.65894775 12.10240772  5.16749604 14.07173523 23.11609593]]
