# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 21, size=2)

r_2 = np.random.randint(1, 21, size=(1, 2))

r_3 = np.random.random(size=(2, 1))

r_4 = np.random.randint(20, 51, size=(3, 5))

r_5 = np.random.randint(1, 100, size=5)

print("r_1:")
print(r_1)

print("\nr_2:")
print(r_2)

print("\nr_3:")
print(r_3)

print("\nr_4:")
print(r_4)

print("\nr_5:")
print(r_5)

r_1:
[8 8]

r_2:
[[ 5 13]]

r_3:
[[0.02214804]
 [0.11166023]]

r_4:
[[34 22 35 41 39]
 [29 34 46 38 48]
 [46 46 29 28 38]]

r_5:
[43 52 32 27 28]


## Permutations

In [3]:
print("Current value of r_4:")
print(r_4)

Current value of r_4:
[[34 22 35 41 39]
 [29 34 46 38 48]
 [46 46 29 28 38]]


In [4]:
np.random.shuffle(r_4)

print("r_4 after using shuffle:")
print(r_4)

r_4 after using shuffle:
[[29 34 46 38 48]
 [34 22 35 41 39]
 [46 46 29 28 38]]


The shuffle function changed the order of the rows in r_4 directly. It did not create a new array. It changed the original r_4 array.

In [5]:
new_shuffle = np.random.permutation(r_4)

print("new_shuffle:")
print(new_shuffle)

print("\nr_4 after using permutation:")
print(r_4)

new_shuffle:
[[46 46 29 28 38]
 [34 22 35 41 39]
 [29 34 46 38 48]]

r_4 after using permutation:
[[29 34 46 38 48]
 [34 22 35 41 39]
 [46 46 29 28 38]]


I would use shuffle when I want to change the original array directly. I would use permutation when I want to create a shuffled copy but keep the original array the same.

## Mathematical Operations

In [6]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

result = np.add(r_1, r_2)

print("\nr_1 + r_2:")
print(result)
print("Shape of result:", result.shape)

r_1:
[8 8]
Shape of r_1: (2,)

r_2:
[[ 5 13]]
Shape of r_2: (1, 2)

r_1 + r_2:
[[13 21]]
Shape of result: (1, 2)


In [7]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_3:")
print(r_3)
print("Shape of r_3:", r_3.shape)

result = np.add(r_1, r_3)

print("\nr_1 + r_3:")
print(result)
print("Shape of result:", result.shape)

r_1:
[8 8]
Shape of r_1: (2,)

r_3:
[[0.02214804]
 [0.11166023]]
Shape of r_3: (2, 1)

r_1 + r_3:
[[8.02214804 8.02214804]
 [8.11166023 8.11166023]]
Shape of result: (2, 2)


In [8]:
print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

print("\nr_4:")
print(r_4)
print("Shape of r_4:", r_4.shape)

try:
    result = np.add(r_2, r_4)
    print("\nr_2 + r_4:")
    print(result)
    print("Shape of result:", result.shape)

except ValueError as error:
    print("\nr_2 + r_4 gives an error:")
    print(error)

r_2:
[[ 5 13]]
Shape of r_2: (1, 2)

r_4:
[[29 34 46 38 48]
 [34 22 35 41 39]
 [46 46 29 28 38]]
Shape of r_4: (3, 5)

r_2 + r_4 gives an error:
operands could not be broadcast together with shapes (1,2) (3,5) 


In [9]:
try:
    print("r_1 + r_4:")
    print(np.add(r_1, r_4))

except ValueError as error:
    print("r_1 + r_4 gives an error:")
    print(error)


try:
    print("\nr_2 + r_4:")
    print(np.add(r_2, r_4))

except ValueError as error:
    print("\nr_2 + r_4 gives an error:")
    print(error)


try:
    print("\nr_3 + r_4:")
    print(np.add(r_3, r_4))

except ValueError as error:
    print("\nr_3 + r_4 gives an error:")
    print(error)

# These errors happen because the shapes of the arrays do not match correctly for broadcasting.

r_1 + r_4:
r_1 + r_4 gives an error:
operands could not be broadcast together with shapes (2,) (3,5) 

r_2 + r_4:

r_2 + r_4 gives an error:
operands could not be broadcast together with shapes (1,2) (3,5) 

r_3 + r_4:

r_3 + r_4 gives an error:
operands could not be broadcast together with shapes (2,1) (3,5) 


In [10]:
print("r_4 + np.array([1]):")
print(np.add(r_4, np.array([1])))

r_4 + np.array([1]):
[[30 35 47 39 49]
 [35 23 36 42 40]
 [47 47 30 29 39]]


In [11]:
print("r_4 + np.array([[1]]):")
print(np.add(r_4, np.array([[1]])))

r_4 + np.array([[1]]):
[[30 35 47 39 49]
 [35 23 36 42 40]
 [47 47 30 29 39]]


In [12]:
print("r_4 + np.array([1, 1, 1, 1, 1]):")
print(np.add(r_4, np.array([1, 1, 1, 1, 1])))

r_4 + np.array([1, 1, 1, 1, 1]):
[[30 35 47 39 49]
 [35 23 36 42 40]
 [47 47 30 29 39]]


In [13]:
try:
    print("r_4 + np.array([[1], [1]]):")
    print(np.add(r_4, np.array([[1], [1]])))

except ValueError as error:
    print("This gives an error:")
    print(error)

# Error reason:
# r_4 has 3 rows and 5 columns.
# np.array([[1], [1]]) has 2 rows and 1 column.
# The row sizes do not match, so NumPy cannot broadcast them together.

r_4 + np.array([[1], [1]]):
This gives an error:
operands could not be broadcast together with shapes (3,5) (2,1) 


Broadcasting is when NumPy tries to stretch a smaller array so it can work with a larger array. When using the add function, NumPy adds values based on matching positions. If one array has a shape that can fit across the other array, NumPy will add it. The shape of the result is usually based on the larger array.

## Rounding

In [15]:
print("r_3:")
print(r_3)

r_3:
[[0.02214804]
 [0.11166023]]


In [16]:
print("Using trunc:")
print(np.trunc(r_3))

Using trunc:
[[0.]
 [0.]]


In [17]:
print("Using fix:")
print(np.fix(r_3))

Using fix:
[[0.]
 [0.]]


In [18]:
print("Using floor:")
print(np.floor(r_3))

Using floor:
[[0.]
 [0.]]


In [19]:
print("Using ceil:")
print(np.ceil(r_3))

Using ceil:
[[1.]
 [1.]]


In [20]:
print("Using round to 2 decimal places:")
print(np.round(r_3, 2))

Using round to 2 decimal places:
[[0.02]
 [0.11]]


## Cumulative Operations

In [21]:
print("r_4:")
print(r_4)

r_4:
[[29 34 46 38 48]
 [34 22 35 41 39]
 [46 46 29 28 38]]


In [22]:
print("Sum of all values in r_4:")
print(np.sum(r_4))

Sum of all values in r_4:
553


In [23]:
print("Sum along axis 0:")
print(np.sum(r_4, axis=0))

Sum along axis 0:
[109 102 110 107 125]


In [24]:
print("Sum along axis 1:")
print(np.sum(r_4, axis=1))

Sum along axis 1:
[195 171 187]


In [25]:
print("Cumulative sum of all values in r_4:")
print(np.cumsum(r_4))

Cumulative sum of all values in r_4:
[ 29  63 109 147 195 229 251 286 327 366 412 458 487 515 553]


In [26]:
print("Cumulative sum along axis 0:")
print(np.cumsum(r_4, axis=0))

Cumulative sum along axis 0:
[[ 29  34  46  38  48]
 [ 63  56  81  79  87]
 [109 102 110 107 125]]


## Grocery Problem

In [27]:
# Order: vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("Bag 1:")
print(bag1)

print("\nBag 2:")
print(bag2)

Bag 1:
[2 3 4 0]

Bag 2:
[4 0 1 2]


In [28]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [29]:
category_totals = bag1 + bag2

print(
    f"There are {category_totals[0]} vegetables, "
    f"{category_totals[1]} fruits, "
    f"{category_totals[2]} boxes of snacks, "
    f"and {category_totals[3]} beverages in the two grocery bags."
)

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [30]:
ali = np.array([5, 4, 6, 4, 2])

In [31]:
ben = np.array([0, 5, 5, 3, 4])

In [32]:
carla = np.array([3, 6, 0, 3, 4])

In [33]:
all_knocks = np.array([ali, ben, carla])

print("All knocks:")
print(all_knocks)

All knocks:
[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [34]:
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print("Total doors knocked by each person:")
print("Ali:", person_totals[0])
print("Ben:", person_totals[1])
print("Carla:", person_totals[2])

print("\nTotal doors knocked by the group:")
print(group_total)

Total doors knocked by each person:
Ali: 21
Ben: 17
Carla: 16

Total doors knocked by the group:
54


In [35]:
daily_totals = np.sum(all_knocks, axis=0)

rolling_total_doors = np.cumsum(daily_totals)

estimated_votes = rolling_total_doors * 0.5

print("Daily totals:")
print(daily_totals)

print("\nRolling total of doors knocked:")
print(rolling_total_doors)

print("\nRolling total of estimated votes:")
print(estimated_votes)

Daily totals:
[ 8 15 11 10 10]

Rolling total of doors knocked:
[ 8 23 34 44 54]

Rolling total of estimated votes:
[ 4.  11.5 17.  22.  27. ]
