# NumPy Array Basics

This exercise introduces the basics of NumPy arrays. I will practice creating one-dimensional, two-dimensional, and three-dimensional arrays, checking data types, using array indexing, and transposing arrays.

In [9]:
import numpy as np

## Array Basics

In [11]:
fruits = ["apple", "banana", "cherry", "date"]
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [12]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [13]:
print(arr_1.dtype)

# The data type returned is usually <U6.
# The U means Unicode string.
# The number 6 means the longest string in the array has 6 characters.
# In this list, "banana" and "cherry" both have 6 characters.

<U6


In [14]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [15]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [16]:
print(arr_2)

# No, arr_2.T does not permanently change the original arr_2.
# It only displays or returns a transposed version of the array.
# The original arr_2 is still stored the same way.

[[10 11 12]
 [13 14 15]]


In [17]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [18]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

[5 4]


In [19]:
arr_5 = np.ones((2, 2, 2), dtype=int)

print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
